id = "sil-lang"
name = "SIL Language Extension"
version = "0.0.1"
schema_version = 1
authors = ["Arnav Patri <arnavpatri1@gmail.com>"]
description = "Support for SIL from UWaterloo's CS 442"
repository = "https://github.com/Endolite/zed-sil"

[grammars.sil]
repository = "https://github.com/Endolite/tree-sitter-sil"
rev = "0d046b4cd6a7f72c5682186c8488963058e94d7c"
